# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [ ]:
import numpy as np
arr1=np.arange(10)
print(arr1)
print('='*50)
arr2=np.zeros(9).reshape(3,3)
print(arr2)
print('='*50)
arr3=np.ones(8).reshape(2,4)
print(arr3)
print('='*50)
arr4=np.identity(3)
print(arr4)
print('='*50)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print('='*50)
print(arr.dtype)
print('='*50)
print(arr.ndim)
print('='*50)
print(arr.nbytes)
print('='*50)

(2, 3)
int64
2
48



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print('='*50)

print(arr[:2])
print('='*50)

print(arr[:,-1])
print('='*50)

print(arr[1,2])
print('='*50)

arr2=arr[-1:-4:-1]
print(arr2)


[[10 20 30]
 [40 50 60]]
[30 60 90]
60
[[70 80 90]
 [40 50 60]
 [10 20 30]]



---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
arr2=arr[arr %2==0]
print(arr2)
print('='*50)

print(arr[1:3])
print('='*50)

print(arr[:,2:4])
print('='*50)

print(arr[1:3,1:3])
print('='*50)


[ 2  4  6  8 10 12 14 16]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_sum=(arr1+arr2)
print(arr_sum)
print('='*50)

arr_mult=(arr1*arr2)
print(arr_mult)
print('='*50)

arr_power=(arr1**2)
print(arr_power)
print('='*50)

[5 7 9]
[ 4 10 18]
[1 4 9]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1], [2]])

res1=A+B
print(res1)
print('='*50)

res2=A*B
print(res2)
print('='*50)

res3=A-5
print(res3)
print('='*50)

res4 = A + C
print(res4)
print('='*50)

[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]
[[-4 -3 -2]
 [-1  0  1]]
[[2 3 4]
 [6 7 8]]



---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [ ]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

res1=A+B
print(res1)
print('='*50)

res2=C*B
print(res2)
print('='*50)

res3=B+5
print(res3)
print('='*50)

[[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
[[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]
[105 205 305 405]



---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [ ]:
arr = np.arange(12).reshape(3,4)
print(arr)
print('='*50)
arr=arr.flatten()
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]



---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [ ]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])

v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))
print(v_stacked)
print('='*50)
print(h_stacked)
print('='*50)

c=np.arange(16).reshape(4,4)
c=c.reshape(2,8)
c

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])


## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [ ]:
arr = np.array([[5, 10, 15], [20, 25, 30]])
print(arr[arr>10])
print('='*50)

arr[arr%2==0]=-1
arr

[15 20 25 30]


array([[ 5, -1, 15],
       [-1, 25, -1]])


---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))
print('='*50)
print(np.mean(arr))
print('='*50)
print(np.max(arr))
print('='*50)
print(np.std(arr))
print('='*50)

21
3.5
6
1.707825127659933



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])


---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [ ]:
arr=np.random.rand(6).reshape(2,3)
print(arr)
arr2=np.random.randint(50,100,10)
print(arr2)

[[0.8641452  0.63730227 0.38421783]
 [0.75504623 0.48291824 0.40625779]]
[52 53 86 97 99 72 71 76 69 85]



---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [ ]:
arr=np.random.randint(50,100,9).reshape(3,3)
print(arr)
print('='*50)
print(np.linalg.matrix_rank(arr))
print('='*50)
print(np.linalg.inv(arr))
print('='*50)
print(np.linalg.det(arr))


[[89 55 68]
 [95 78 75]
 [71 65 80]]
3
[[ 0.03440367  0.00050408 -0.0297157 ]
 [-0.05733945  0.05776792 -0.00541889]
 [ 0.01605505 -0.04738381  0.04327553]]
39675.999999999985



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [ ]:

arr=np.arange(36).reshape(6,6)
print(arr)
print('='*50)
lst=[]

for i in range(3):
  for j in range(3):
   lst.append(int(arr[i,j]))
print('='*50)
print(lst)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[0, 1, 2, 6, 7, 8, 12, 13, 14]



---

Happy coding! 🎯
